const asyncHandler = require('express-async-handler'); const User = require('../models/User'); const Product = require('../models/Product'); const Order = require('../models/Order');
exports.profile = asyncHandler(async (req, res) => {
  if (req.body.password && req.body.password.length < 8) return res.status(400).json({ message: 'Password must be at least 8 characters.' });
  Object.assign(req.user, { name: req.body.name ?? req.user.name, phone: req.body.phone ?? req.user.phone, address: req.body.address ?? req.user.address }); if (req.body.password) req.user.password = req.body.password; await req.user.save(); res.json({ _id: req.user._id, name: req.user.name, email: req.user.email, role: req.user.role, phone: req.user.phone, address: req.user.address });
});
exports.list = asyncHandler(async (req, res) => res.json(await User.find().select('-password').sort({ createdAt: -1 })));
exports.updateRole = asyncHandler(async (req, res) => { const user = await User.findById(req.params.id); if (!user) return res.status(404).json({ message: 'User not found.' }); if (!['customer', 'seller', 'admin'].includes(req.body.role)) return res.status(400).json({ message: 'Invalid role.' }); user.role = req.body.role; await user.save(); res.json({ _id: user._id, name: user.name, email: user.email, role: user.role }); });
exports.remove = asyncHandler(async (req, res) => { if (String(req.user._id) === req.params.id) return res.status(400).json({ message: 'You cannot delete your own account here.' }); const user = await User.findByIdAndDelete(req.params.id); if (!user) return res.status(404).json({ message: 'User not found.' }); res.json({ message: 'User removed.' }); });
exports.stats = asyncHandler(async (req, res) => { const [users, sellers, products, orders, revenue] = await Promise.all([User.countDocuments(), User.countDocuments({ role: 'seller' }), Product.countDocuments(), Order.countDocuments(), Order.aggregate([{ $match: { status: { $ne: 'cancelled' } } }, { $group: { _id: null, total: { $sum: '$total' } } }])]); res.json({ users, sellers, products, orders, revenue: revenue[0]?.total || 0 }); });
