import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { Menu, Leaf, ShoppingBag, UserRound, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext'; import { useCart } from '../context/CartContext';
export function Navbar() {
  const { user, logout } = useAuth(); const { count } = useCart(); const [open, setOpen] = useState(false);
  const links = [['Shop', '/products'], ...(user ? [['My orders', '/orders']] : []), ...(user?.role === 'seller' ? [['Seller studio', '/seller']] : []), ...(user?.role === 'admin' ? [['Admin', '/admin']] : [])];
  return <><div className="announcement">GROW BETTER, TOGETHER <span>✦</span> Thoughtful supplies for every season</div><header className="navbar"><div className="nav-inner"><Link to="/" className="brand"><span className="brand-mark"><Leaf size={23}/></span><span>agri<span className="brand-light">sphere</span></span></Link><nav className={open ? 'nav-links open' : 'nav-links'}>{links.map(([name, to]) => <NavLink key={to} to={to} onClick={() => setOpen(false)}>{name}</NavLink>)}</nav><div className="nav-actions"><Link to="/cart" className="icon-link cart-link" aria-label="Shopping cart"><ShoppingBag size={20}/><span>Bag{count > 0 && <b>{count}</b>}</span></Link>{user ? <div className="account-nav"><Link to="/profile" className="account-chip"><span className="avatar-mini">{user.name?.[0]}</span><span>{user.name?.split(' ')[0]}</span></Link><button className="text-button" onClick={logout}>Log out</button></div> : <Link to="/login" className="signin">Sign in <span>↗</span></Link>}<button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button></div></div></header></>;
}
export function Footer() { return <footer className="footer"><div className="footer-main"><div><Link to="/" className="brand footer-brand"><span className="brand-mark"><Leaf size={21}/></span><span>agri<span className="brand-light">sphere</span></span></Link><p>Good things grow here.<br/>Thoughtful supplies for your land.</p></div><div className="footer-links"><div><strong>Explore</strong><Link to="/products">Shop all</Link><Link to="/products?category=Seeds">Seeds</Link><Link to="/products?category=Organic%20Products">Organic goods</Link></div><div><strong>Your account</strong><Link to="/profile">Profile</Link><Link to="/orders">Orders</Link><Link to="/cart">Shopping bag</Link></div></div></div><div className="footer-bottom"><span>© 2025 AgriSphere. Made for growers.</span><span>Rooted in good things <span className="heart">♥</span></span></div></footer>; }
export function Shell({ children }) { return <><Navbar/><main>{children}</main><Footer/></>; }
