import { useEffect, useState } from 'react'; import { Link, useNavigate } from 'react-router-dom'; import { ArrowDown, ArrowRight, ArrowUpRight, Sprout, Truck, ShieldCheck, HandHeart } from 'lucide-react'; import api from '../api'; import { ProductCard } from '../components/ProductCard'; import { useCart } from '../context/CartContext';
const cats = [{ name: 'Seeds', icon: '🌱', color: 'sage' }, { name: 'Fertilizers', icon: '🪴', color: 'peach' }, { name: 'Pesticides', icon: '🌿', color: 'yellow' }, { name: 'Farming Tools', icon: '🧤', color: 'lavender' }, { name: 'Irrigation Equipment', icon: '💧', color: 'blue' }, { name: 'Organic Products', icon: '🍃', color: 'sage' }, { name: 'Animal Feed', icon: '🐄', color: 'peach' }, { name: 'Gardening Products', icon: '🌷', color: 'yellow' }];
export default function Home() { const [products, setProducts] = useState([]); const [query, setQuery] = useState(''); const nav = useNavigate(); const { add } = useCart(); useEffect(() => { api.get('/products?featured=true').then(r => setProducts(r.data.slice(0, 4))).catch(() => {}); }, []); const search = e => { e.preventDefault(); nav(`/products${query ? `?search=${encodeURIComponent(query)}` : ''}`); };
 return <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-dot"/> THE GROWER'S GOOD GUIDE</span><h1>Good things<br/>grow <em>here.</em></h1><p>Better harvests start with the right things.<br/>Find thoughtful supplies, picked for the way you grow.</p><form className="hero-search" onSubmit={search}><span>⌕</span><input aria-label="Search products" value={query} onChange={e => setQuery(e.target.value)} placeholder="What are you growing today?"/><button aria-label="Search"><ArrowRight size={18}/></button></form><div className="hero-note"><span className="avatar-stack"><i>🌾</i><i>🌱</i><i>🍅</i></span><span>Loved by <strong>2,400+</strong> growers across India</span></div></div><div className="hero-visual"><div className="hero-image"/><div className="hero-float"><div className="float-icon"><Sprout size={20}/></div><div><b>Grow with care</b><span>Good soil. Good seasons.</span></div><span className="float-arrow">↗</span></div><span className="hero-stamp">FROM SEED<br/>TO HARVEST <span>✳</span></span><span className="hero-side-note">A LITTLE MORE GREEN IN EVERYDAY LIFE</span></div><a className="scroll-hint" href="#categories"><ArrowDown size={14}/> SCROLL TO EXPLORE</a><span className="hero-number">01 <i/> 04</span></section>
  <section className="benefits"><div><span><Truck size={18}/></span><p><b>Careful delivery</b><small>Across India, to your door</small></p></div><div><span><ShieldCheck size={18}/></span><p><b>Grower-approved</b><small>Quality you can count on</small></p></div><div><span><HandHeart size={18}/></span><p><b>Rooted in community</b><small>Supporting local sellers</small></p></div><div className="benefit-note">Made for your patch of earth <span>✳</span></div></section>
  <section className="section categories-section" id="categories"><div className="section-head"><div><span className="eyebrow">A PLACE FOR EVERYTHING</span><h2>Find your kind<br/><em>of growing.</em></h2></div><Link className="round-link" to="/products">Explore all <ArrowUpRight size={18}/></Link></div><div className="category-grid">{cats.map(c => <Link to={`/products?category=${encodeURIComponent(c.name)}`} className={`category-tile ${c.color}`} key={c.name}><span className="category-emoji">{c.icon}</span><span><b>{c.name}</b><small>Thoughtful picks for you</small></span><ArrowUpRight size={17}/></Link>)}</div></section>
  <section className="section featured-section"><div className="section-head"><div><span className="eyebrow">THE GOOD STUFF</span><h2>Growers are loving <em>these.</em></h2></div><Link className="text-link" to="/products">See everything <ArrowRight size={16}/></Link></div>{products.length ? <div className="product-grid">{products.map(p => <ProductCard key={p._id} product={p} onAdd={p => add(p._id).catch(e => alert(e.response?.data?.message || 'Please sign in to add items.'))}/>)}</div> : <div className="empty-feature"><span>🌿</span><p>Fresh picks are finding their way here.</p><small>Start the API and seed your garden to see products.</small></div>}</section>
  <section className="grow-banner"><div><span className="eyebrow">FOR THE ONES WHO GROW</span><h2>Your next good<br/>season starts <em>here.</em></h2><p>A small idea, a big field, or a sunny windowsill —<br/>there's something good growing for everyone.</p><Link className="light-button" to="/products">Find your growing things <ArrowRight size={16}/></Link></div><div className="banner-art"><div className="banner-art-img"/><span className="banner-caption">GROWN WITH A LITTLE MORE CARE <i>✳</i></span><span className="banner-leaf">✳</span></div><span className="banner-vertical">TAKE THE SCENIC ROUTE</span></section>
 </>; }
